language: node_js
node_js:
  - '8.12'
env:
  matrix:
    secure: VKwcAJHWkhw5FiIsg46tPLcsvotU/5rjpOMI4CfpkWrtq4h8G90ByiD3tsdRz/P+5qdGN6jk6DKZXxzZqLtHNeybzHqBMh2Vgv0Z9oloRi6W9z0wmoywvC3GSEGl0Ln5rkwqALxslTe47j9/yLz4t/eTQ/DMz6ViWrn1+RJuiPst7rvw++uFAAd6Jl7pSi5N+attzyD/2DbHtP/4EKl0m97c9HMRWesbb4IAi8Vofk8gh9yCwlDEMuu7ubR7sLzExiLhM4ccRAdC2awxBW4380C3b/tN/aXyen1GPsNUwxjhq4xjuT4vAaGh7uYodEcuikuf7ZOmN3syWwCq/X32dEMXRtDvczTRiWdr1x3vBCiLcHtubaxpqyRDp9GgzIpAMbBebBcrx9vzVZvKyR3IxofavW5nU9c1nYQfvK5snKWaTkUglNgbMfaQQDpDNLQnlF9l7uK3E0T+g5qhL+MRLlj5Nn5IAVpXCy4r17dnWgDsgTVvsK1pCE+eXz+h5omiCgF08nlfNWHY259ch670OnAxa80Lc73yooE3713XaqyRjasSHq301prAmKwUqV+QKYA7zh2kQhTn2MEq4cJbIWBzQlfAf88zFpCLrOUClg6qB+gNRkZiZZ2OAb5r/Gn5yQ0zOWRcsy2ZMB4Z/G5SM0+SzZeRgAoQ9BG7qQ29FB0=
script:
  - node .build.js
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: '$GITHUB_TOKEN'
  branches:
    only:
      - master
